# Generated by Django 5.2.8 on 2025-11-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trashmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=25)),
            ],
        ),
    ]
